name: CI

on:
  push:
    branches:
      - build

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set-projects.outputs.projects }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Get affected projects
        id: set-projects
        run: |
          PROJECTS=$(npx nx show projects --type app -t build --affected --base=origin/main --json)
          echo "projects=$PROJECTS" >> $GITHUB_OUTPUT

  build:
    if: needs.setup.outputs.projects != '[]'
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.setup.outputs.projects) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Build
        run: npx nx run ${{ matrix.project }}:build

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print docker step
        run: echo "docker"

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy step
        run: echo "deploy"

  done:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Print done step
        run: echo "done"
