name: CI

on:
  push:
    branches:
      - build

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set-projects.outputs.projects }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Get affected projects
        id: set-projects
        run: |
          PROJECTS=$(npx nx show projects --type app -t build --affected --base=origin/main --json)
          echo "projects=$PROJECTS" >> $GITHUB_OUTPUT

  build:
    if: needs.setup.outputs.projects != '[]'
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.setup.outputs.projects) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Build
        run: npx nx run ${{ matrix.project }}:build:production
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project }}-build
          path: dist/apps/${{ matrix.project }}

  deploy:
    needs:
      - setup
      - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.setup.outputs.projects) }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            .github
            infra
      - name: Extract environment variables
        env:
          PROJECT_NAME: ${{ matrix.project }}
          ALL_VARS_JSON: ${{ toJson(vars) }}
          ALL_SECRETS_JSON: ${{ toJson(secrets) }}
        run: |
          node ./.github/scripts/extract-variables.js
      - name: Download build artifact
        if: ${{ !cancelled() && (hashFiles(format('infra/{0}/**', matrix.project)) != '') }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.project }}-build
          path: dist/apps/${{ matrix.project }}
      - name: Deploy with Terraform
        if: ${{ !cancelled() && (hashFiles(format('infra/{0}/**', matrix.project)) != '') }}
        uses: ./.github/actions/terraform-deploy
        with:
          nx_project: ${{ matrix.project }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          setup_firebase: ${{ endsWith(matrix.project, '-ngx') }}

  done:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Print done step
        run: echo "done"
